// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"encoding/json"
	"time"
)

type Datamodel struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Version struct {
	ID         int64           `json:"id"`
	ObjectType string          `json:"object_type"`
	ObjectID   int64           `json:"object_id"`
	Json       json.RawMessage `json:"json"`
	Version    int32           `json:"version"`
	Action     string          `json:"action"`
	Actor      string          `json:"actor"`
	CreatedAt  time.Time       `json:"created_at"`
}
